http:
  routers:
    prometheus-rtr:
      rule: 'Host(`prometheus.{{ env "DOMAINNAME_1" }}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-authelia
      service: prometheus-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file

  services:
    prometheus-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: "prometheus"
        servers:
          - url: 'http://{{ env "SERVERIP_CRITICAL" }}:9090'

  serversTransports:
    prometheus:
      insecureSkipVerify: true